videojs.registerPlugin('pluginDev', function() {
    var player = this,
        overlayEl = document.createElement('p'),
        overlayComponent = new (videojs.getComponent('Component'))(player),
        closeBtn = document.createElement('button'),
        btnSpan  = document.createElement('span');

    overlayEl.className = 'vjs-overlay';
    overlayEl.textContent = "The captions have been automatically generated by YouTube, and have not been reviewed for accuracy.";
    btnSpan.className = 'vjs-icon-cancel';

    closeBtn.appendChild(btnSpan);
    overlayEl.appendChild(closeBtn);
    overlayComponent.el().appendChild(overlayEl);

    // Add event listener on Close Button
    closeBtn.addEventListener('click', function() {
        player.removeChild(overlayComponent);
    });

    // Add handler for displaying disclaimer when captions button is clicked.
    if (player.controlBar?.subsCapsButton) { // If captions exists.
        player.controlBar.subsCapsButton.on('click', function() {
            // Check if user was already displayed disclaimer when first clicked on captions button
            var alreadyDisplayed = window.localStorage.getItem("ajCapsDisclaimerDisplayed");
            // If it's not already displayed then only we will be displaying the disclaimer.
            if (!alreadyDisplayed) {
                window.localStorage.setItem("ajCapsDisclaimerDisplayed", true);
                if (!player.getChildById(overlayComponent)) {
                    player.addChild(overlayComponent);
                }
                console.log('clicked');
                player.setTimeout(function(){
                    if (player.getChildById(overlayComponent)) {
                        player.removeChild(overlayComponent);
                    }
                }, 5000);
            }
        });
    }

    // Add info button for manually seeing the disclaimer
    const ButtonComponent = videojs.getComponent('Button')
    const infoIcon = document.createElement('span');
    infoIcon.textContent = 'ⓘ';

    const button = new ButtonComponent(player, {
        controlText: 'Captions Disclaimer',
        className: 'vjs-disclaimer-close-btn',
        clickHandler: function() {
            if (!player.getChildById(overlayComponent)) {
                player.addChild(overlayComponent);
            }
            console.log('clicked');
            player.setTimeout(function(){
                if (player.getChildById(overlayComponent)) {
                    player.removeChild(overlayComponent);
                }
            }, 5000);
        },
    });

    button.el().appendChild(infoIcon);
    player.getChild('ControlBar').addChild(button, {}, 10);
  });



// const Buttom = videojs.getComponent('Button')

// const button = new Button(player, {
//     clickHandler: function() {
//         // Code for displaying disclaimer goes here
//     }
// })

// player.getChild('ControlBar').addChild(button)

// const ccButton = player.controlBar.subsCapsButton
// ccButton.removeChild(ccButton.menu)


// player.on('loadeddata', function() {
//     player.textTracks().getTrackById('English').mode = 'showing';
// });