videojs.registerPlugin('pluginDev', function() {
    var player = this;
    var overlay = document.createElement('p');
    overlay.className = 'vjs-overlay';
    overlay.innerHTML = "The captions have been automatically generated by YouTube, and have not been reviewed for accuracy.";

    var closeBtn = document.createElement('button');
    var btnSpan  = document.createElement('span');
    btnSpan.className = 'vjs-icon-cancel';
    closeBtn.appendChild(btnSpan);
    overlay.appendChild(closeBtn);

    // Add event listener on Close Button
    closeBtn.addEventListener('click', function() {
        player.el().removeChild(overlay);
    });

    // Add handler for displaying disclaimer when captions button is clicked.
    player.controlBar.subsCapsButton.on('click', function() {
        // Check if user was already displayed disclaimer when first clicked on captions button
        var alreadyDisplayed = window.localStorage.getItem("ajCapsDisclaimerDisplayed");
        if (!alreadyDisplayed) {
            window.localStorage.setItem("ajCapsDisclaimerDisplayed", true);
            player.el().removeChild(overlay);
            player.el().appendChild(overlay);
            player.setTimeout(function(){
                player.el().removeChild(overlay);
            }, 5000);
        }
    })


    // Add info button for manually seeing the disclaimer
    const Button = videojs.getComponent('Button')
    const infoIcon = document.createElement('span');
    infoIcon.innerHTML = 'ⓘ';

    const button = new Button(player, {
        controlText: 'Captions Disclaimer',
        clickHandler: function() {
            player.el().removeChild(overlay);
            player.el().appendChild(overlay);
            player.setTimeout(function(){
                player.el().removeChild(overlay);
            }, 5000);
        },
    });

    button.el().appendChild(infoIcon);

    player.getChild('ControlBar').addChild(button, {}, 10);
  });



// const Buttom = videojs.getComponent('Button')

// const button = new Button(player, {
//     clickHandler: function() {
//         // Code for displaying disclaimer goes here
//     }
// })

// player.getChild('ControlBar').addChild(button)

// const ccButton = player.controlBar.subsCapsButton
// ccButton.removeChild(ccButton.menu)


// player.on('loadeddata', function() {
//     player.textTracks().getTrackById('English').mode = 'showing';
// });